ecommerce_pipeline:
  target: dev
  outputs:
    dev:
      type: postgres
      host: localhost
      user: postgres
      password: 1234
      port: 5432
      dbname: ecommerce_pipeline
      schema: gold        # default write schema for models
      threads: 4